import { Jost, Roboto } from 'next/font/google'

import Footer from '@/components/Footer/Footer'
import { Header } from '@/components/Header/Header'

import type { Metadata } from 'next'

import './globals.css'

const roboto = Roboto({
  subsets: ['cyrillic', 'latin'],
  weight: ['300', '400', '500', '700'],
  display: 'swap',
  variable: '--primary-font',
  style: ['normal']
})

const jost = Jost({
  subsets: ['cyrillic', 'latin'],
  weight: ['300', '400', '500', '700'],
  display: 'swap',
  variable: '--secondary-font',
  style: ['normal']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.variable} ${jost.variable} bg-[#f7f7f7] antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
